[package]
name = "teloxide"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0.44"
serde = { version = "1.0.101", features = ["derive"] }

tokio = { version = "0.2.6", features = ["full"] }
tokio-util = { version = "0.2.0", features = ["full"] }

reqwest = { version = "0.10", features = ["json", "stream", "native-tls-vendored"] }
log = "0.4.8"
bytes = "0.5.3"
mime = "0.3.16"

derive_more = "0.99.2"
thiserror = "1.0.9"
async-trait = "0.1.22"
duang = "0.1.2"
futures = "0.3.1"
pin-project = "0.4.6"
serde_with_macros = "1.0.1"
either = "1.5.3"

regex = "1.3.4"

[build-dependencies]
serde_json = "1.0.44"
quote = "1.0"
